### ISSUE TITLE
Does not recognice `~` in dependency version

### ISSUE THREAD

**Issue by tarantelklient** [KalavarDB/utilities#2] opened 2021-01-14 07:36 UTC
Hey there,

I just tried your tool, but got an error: In my Cargo.toml are some `~` to specify my versions, see here in the rust book: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements

Here is a snippet from a version with a `~`
```toml
[dependencies]
base64 = "~0.13"
```

This is the error:

```
======================> Crate Version Checker 0.1 <======================
Advisories  Crate                                        Version
=========================================================================
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("encountered unexpected token: Tilde")', <PATH TO HOME>/.cargo/registry/src/github.com-1ecc6299db9ec823/version-checker-0.1.0/src/main.rs:193:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm working on a MacBook Pro (Intel). Do you need further information?

**Comment by fatalcenturion** [comment] 2021-01-14 10:13
Firstly, thank you for opening your issue, it means a lot to me that you use the program, and it also upsets me that it does not work for you. 

I am aware of an issue when parsing version numbers which should not exist because of how basic it is. I am happy to share that this issue should be fixed in the next version of it, which I preemptively began work on yesterday. This new version adds a lot more complexity to the parsing system, which was originally all monolithic and 1 file, obviously this is bad for maintainability so im working on breaking it into different modules, and in the process of doing so im adding more complexity to the parsing system to allow it to process the chracter patterns necessary to make it work across the (hopefully) all possible valid Cargo.toml files.

If you are curious how the changes I am making fix this, you can take a look in <this repo>/version-checker/src/management/crates_io.rs, in this new version there is much more opportunity to successfully parse a version string, and, a miniscule chance of it actually panicking. 

Once more, I apologise it didnt work for you, I do have a fix coming, but because of college schedules it might be a week or so before I can release it fully, ill send a comment here when I do though :)

**Comment by tarantelklient** [comment] 2021-01-14 10:17
You're welcome, I'm always eager to test new thinks out and your program was exactly what I was missing.

Ok, I'll test it again after you finished the changes! Take your time :)

**Comment by fatalcenturion** [comment] 2021-01-15 02:21
well, long story short, it appears i lied, i managed to find some time, and i am pushing version 0.1.1 to crates.io as i write this comment.
Im going to close this issue now as it should be fixed with the latest update. I will be happy to reopen it if you can reproduce the issue once more, but i did test it on a variety of different Cargo manifests from multiple large projects such as Cargo itself without issue.

**Closed by fatalcenturion** 2021-01-15 02:21 UTC

**Comment by tarantelklient** [comment] 2021-01-15 06:50
It's working fine now, thank you very much!
